### PR TITLE
deploy用

### PR DESCRIPTION
**Pull request by aqla114**

### CODE REVIEW

**Comment by ghost** [comment]
deployed! https://turenar.xyz/mayfes-pikyou/deployment

**Comment by ghost** [comment]
deployed! https://turenar.xyz/mayfes-pikyou/deployment

**Review by turenar — APPROVED** [review]

**Comment by ghost** [comment]
deployed! https://turenar.xyz/mayfes-pikyou/deployment

**Comment by aqla114** [comment]
2の方をmergeしたのでこっちは閉じます。

**Pull request closed without merging**
